# Type stubs for `pyspark.pipelines` as available on Databricks (generated by zed-databricks).
#
# OSS Spark (4.1+) ships inline types for the core API but not the Databricks-only additions:
# expectations, SCD type 2 / history tracking in AUTO CDC, snapshot CDC, sink helpers and the
# extra dataset options. This is a partial stub package (see py.typed): other `pyspark`
# modules still resolve to the installed package.

from collections.abc import Callable
from typing import Literal, TypeAlias, TypeVar, overload

from pyspark.sql import Column, DataFrame
from pyspark.sql.types import StructType

QueryFunction: TypeAlias = Callable[[], DataFrame]
_F = TypeVar("_F", bound=Callable[..., object])
_ColumnList: TypeAlias = list[str] | list[Column]

# --- datasets ---------------------------------------------------------------------------

@overload
def table(query_function: QueryFunction, /) -> None: ...
@overload
def table(
    query_function: None = None,
    *,
    name: str | None = None,
    comment: str | None = None,
    spark_conf: dict[str, str] | None = None,
    table_properties: dict[str, str] | None = None,
    path: str | None = None,
    partition_cols: list[str] | None = None,
    cluster_by_auto: bool = False,
    cluster_by: list[str] | None = None,
    schema: StructType | str | None = None,
    row_filter: str | None = None,
    private: bool = False,
    format: str | None = None,
) -> Callable[[QueryFunction], None]: ...
@overload
def materialized_view(query_function: QueryFunction, /) -> None: ...
@overload
def materialized_view(
    query_function: None = None,
    *,
    name: str | None = None,
    comment: str | None = None,
    spark_conf: dict[str, str] | None = None,
    table_properties: dict[str, str] | None = None,
    path: str | None = None,
    partition_cols: list[str] | None = None,
    cluster_by_auto: bool = False,
    cluster_by: list[str] | None = None,
    schema: StructType | str | None = None,
    row_filter: str | None = None,
    private: bool = False,
    format: str | None = None,
) -> Callable[[QueryFunction], None]: ...
@overload
def temporary_view(query_function: QueryFunction, /) -> None: ...
@overload
def temporary_view(
    query_function: None = None,
    *,
    name: str | None = None,
    comment: str | None = None,
    spark_conf: dict[str, str] | None = None,
) -> Callable[[QueryFunction], None]: ...
def create_streaming_table(
    name: str,
    *,
    comment: str | None = None,
    spark_conf: dict[str, str] | None = None,
    table_properties: dict[str, str] | None = None,
    path: str | None = None,
    partition_cols: list[str] | None = None,
    cluster_by_auto: bool = False,
    cluster_by: list[str] | None = None,
    schema: StructType | str | None = None,
    expect_all: dict[str, str] | None = None,
    expect_all_or_drop: dict[str, str] | None = None,
    expect_all_or_fail: dict[str, str] | None = None,
    row_filter: str | None = None,
    format: str | None = None,
) -> None: ...

# --- flows ------------------------------------------------------------------------------

def append_flow(
    *,
    target: str,
    name: str | None = None,
    comment: str | None = None,
    spark_conf: dict[str, str] | None = None,
    once: bool = False,
) -> Callable[[QueryFunction], None]: ...
def create_auto_cdc_flow(
    target: str,
    source: str,
    keys: _ColumnList,
    sequence_by: str | Column,
    *,
    system_sequence_by: str | Column | None = None,
    ignore_null_updates: bool = False,
    ignore_null_updates_column_list: _ColumnList | None = None,
    ignore_null_updates_except_column_list: _ColumnList | None = None,
    columns_to_update: str | Column | None = None,
    apply_as_deletes: str | Column | None = None,
    apply_as_truncates: str | Column | None = None,
    column_list: _ColumnList | None = None,
    except_column_list: _ColumnList | None = None,
    stored_as_scd_type: Literal[1, 2, "1", "2"] | None = None,
    track_history_column_list: _ColumnList | None = None,
    track_history_except_column_list: _ColumnList | None = None,
    name: str | None = None,
    once: bool = False,
) -> None: ...
def create_auto_cdc_from_snapshot_flow(
    target: str,
    source: str | Callable[[int | None], tuple[DataFrame, int] | None],
    keys: _ColumnList,
    *,
    stored_as_scd_type: Literal[1, 2, "1", "2"] | None = None,
    track_history_column_list: _ColumnList | None = None,
    track_history_except_column_list: _ColumnList | None = None,
) -> None: ...

# --- expectations (Databricks) ------------------------------------------------------------
# Apply them between the dataset decorator and the function:
#     @dp.table()
#     @dp.expect("valid_id", "id IS NOT NULL")
#     def events(): ...

def expect(description: str, constraint: str) -> Callable[[_F], _F]: ...
def expect_or_drop(description: str, constraint: str) -> Callable[[_F], _F]: ...
def expect_or_fail(description: str, constraint: str) -> Callable[[_F], _F]: ...
def expect_all(expectations: dict[str, str]) -> Callable[[_F], _F]: ...
def expect_all_or_drop(expectations: dict[str, str]) -> Callable[[_F], _F]: ...
def expect_all_or_fail(expectations: dict[str, str]) -> Callable[[_F], _F]: ...

# --- sinks --------------------------------------------------------------------------------

def create_sink(name: str, format: str, options: dict[str, str] | None = None) -> None: ...
def foreach_batch_sink(*, name: str) -> Callable[[Callable[[DataFrame, int], None]], None]: ...
