# Databricks runtime globals for Pyright / basedpyright (generated by zed-databricks).
# `dbutils`, `display` and `displayHTML` are fully typed when `databricks-sdk` (or
# `databricks-connect`) is installed in the project environment; otherwise they are just defined.

from databricks.sdk.runtime import dbutils as dbutils
from databricks.sdk.runtime import display as display
from databricks.sdk.runtime import displayHTML as displayHTML
from pyspark import SparkContext
from pyspark.sql import SparkSession

spark: SparkSession
sc: SparkContext
