#!/bin/sh
# Runs `databricks <args>` for this project, printing the bundle target and CLI profile first.
# Zed's tasks call it, and get DATABRICKS_BUNDLE_TARGET / DATABRICKS_CONFIG_PROFILE from
# `terminal.env` in .zed/settings.json. Generated by zed-databricks; safe to edit.
#
# The tasks go through this script instead of doing this inline, because Zed pre-expands
# `${VAR:-default}` in task commands, and WSL projects add a quoting layer that mangles nested
# quotes. A plain `sh .zed/databricks/cli.sh <args>` survives both.
#
# A trailing `--serverless-version` without a value gets DATABRICKS_SERVERLESS_VERSION
# (default 5, the CLI's own default for serverless).
set -eu

echo "▶ bundle target: ${DATABRICKS_BUNDLE_TARGET:-<bundle default>} | profile: ${DATABRICKS_CONFIG_PROFILE:-<DEFAULT>}"

last=
for arg in "$@"; do last=$arg; done
if [ "$last" = "--serverless-version" ]; then
    set -- "$@" "${DATABRICKS_SERVERLESS_VERSION:-5}"
fi

exec databricks "$@"
