"""Run (or debug) a local Python file against Databricks compute with Databricks Connect.

    python .zed/databricks/connect_runner.py [options] FILE [ARGS...]
    python .zed/databricks/connect_runner.py [options] -m MODULE [ARGS...]

Driver-side code runs locally, so debugpy breakpoints work as usual, while Spark work runs
remotely. Before running the file this creates the Databricks Connect session and provides
the Databricks runtime globals `spark`, `dbutils` and `display`, so notebook-style scripts
run unchanged.

Options (each also resolved as described):
  --profile NAME     ~/.databrickscfg profile.   Else DATABRICKS_CONFIG_PROFILE, else the
                     project's .zed/settings.json terminal.env, else the CLI default.
  --target NAME      bundle target used to find the cluster (same resolution with
                     DATABRICKS_BUNDLE_TARGET).
  --cluster-id ID    run on this cluster.        Else DATABRICKS_CLUSTER_ID, else the bundle
                     target's `cluster_id`, else serverless.
  --serverless       force serverless compute.

Needs `databricks-connect` in the Python environment running this script (its version must
match the compute: https://docs.databricks.com/dev-tools/databricks-connect/). Generated by
zed-databricks; safe to edit.
"""

from __future__ import annotations

import builtins
import json
import os
import re
import runpy
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

TARGET_ENV = "DATABRICKS_BUNDLE_TARGET"
PROFILE_ENV = "DATABRICKS_CONFIG_PROFILE"
CLUSTER_ENV = "DATABRICKS_CLUSTER_ID"


@dataclass
class Options:
    profile: str | None = None
    target: str | None = None
    cluster_id: str | None = None
    serverless: bool = False
    module: str | None = None
    file: str | None = None
    args: list[str] | None = None


@dataclass
class Compute:
    profile: str | None
    cluster_id: str | None
    source: str

    def describe(self) -> str:
        where = f"cluster {self.cluster_id}" if self.cluster_id else "serverless"
        return f"Databricks Connect: {where} ({self.source}), profile {self.profile or 'DEFAULT'}"


def parse_args(argv: list[str]) -> Options:
    options = Options()
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg in ("--profile", "--target", "--cluster-id") and i + 1 < len(argv):
            setattr(options, arg[2:].replace("-", "_"), argv[i + 1])
            i += 2
        elif arg == "--serverless":
            options.serverless = True
            i += 1
        elif arg == "-m" and i + 1 < len(argv):
            options.module, options.args = argv[i + 1], argv[i + 2 :]
            return options
        elif arg in ("-h", "--help"):
            print(__doc__)
            raise SystemExit(0)
        else:
            options.file, options.args = arg, argv[i + 1 :]
            return options
    raise SystemExit("usage: connect_runner.py [options] FILE [ARGS...] | -m MODULE [ARGS...]")


def strip_jsonc(text: str) -> str:
    """Zed settings allow comments and trailing commas."""
    out, i, in_string = [], 0, False
    while i < len(text):
        c = text[i]
        if in_string:
            out.append(c)
            if c == "\\" and i + 1 < len(text):
                out.append(text[i + 1])
                i += 1
            elif c == '"':
                in_string = False
        elif c == '"':
            in_string = True
            out.append(c)
        elif text.startswith("//", i):
            while i < len(text) and text[i] != "\n":
                i += 1
            continue
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = len(text) if end < 0 else end + 2
            continue
        else:
            out.append(c)
        i += 1
    return re.sub(r",(\s*[}\]])", r"\1", "".join(out))


def zed_terminal_env(start: Path) -> dict[str, str]:
    for directory in [start, *start.parents]:
        settings = directory / ".zed" / "settings.json"
        if settings.is_file():
            try:
                env = json.loads(strip_jsonc(settings.read_text())).get("terminal", {}).get("env", {})
            except (json.JSONDecodeError, AttributeError):
                return {}
            return {k: v for k, v in env.items() if isinstance(v, str)}
    return {}


def find_bundle_root(start: Path) -> Path | None:
    for directory in [start, *start.parents]:
        if (directory / "databricks.yml").is_file() or (directory / "databricks.yaml").is_file():
            return directory
    return None


def bundle_cluster_id(root: Path, target: str | None, profile: str | None) -> str | None:
    """`cluster_id` of the bundle target, from the CLI's resolved configuration."""
    cli = os.environ.get("DATABRICKS_CLI_PATH") or shutil.which("databricks")
    if not cli:
        return None
    command = [cli, "bundle", "validate", "--output", "json"]
    if target:
        command += ["--target", target]
    if profile:
        command += ["--profile", profile]
    try:
        result = subprocess.run(command, cwd=root, capture_output=True, text=True, timeout=120)
        return (json.loads(result.stdout).get("bundle") or {}).get("cluster_id")
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        return None


def resolve(options: Options, start: Path, environ: dict[str, str]) -> Compute:
    terminal_env = zed_terminal_env(start)

    def pick(explicit: str | None, name: str) -> str | None:
        return explicit or environ.get(name) or terminal_env.get(name) or None

    profile = pick(options.profile, PROFILE_ENV)
    if options.serverless:
        return Compute(profile, None, "--serverless")
    if options.cluster_id:
        return Compute(profile, options.cluster_id, "--cluster-id")
    if cluster := pick(None, CLUSTER_ENV):
        return Compute(profile, cluster, CLUSTER_ENV)
    target = pick(options.target, TARGET_ENV)
    if root := find_bundle_root(start):
        if cluster := bundle_cluster_id(root, target, profile):
            return Compute(profile, cluster, f"bundle target {target or '(default)'}")
    return Compute(profile, None, "default")


def create_session(compute: Compute):
    from databricks.connect import DatabricksSession

    builder = DatabricksSession.builder
    if compute.profile:
        builder = builder.profile(compute.profile)
    builder = builder.clusterId(compute.cluster_id) if compute.cluster_id else builder.serverless(True)
    return builder.getOrCreate()


def install_globals(session, compute: Compute) -> None:
    """The names Databricks notebooks and jobs get for free."""
    builtins.spark = session  # type: ignore[attr-defined]

    def display(value=None, *args, **kwargs):
        if hasattr(value, "show") and hasattr(value, "schema"):
            value.show(truncate=False)
        elif value is not None:
            print(value)

    builtins.display = display  # type: ignore[attr-defined]
    try:
        from databricks.sdk import WorkspaceClient

        builtins.dbutils = WorkspaceClient(profile=compute.profile).dbutils  # type: ignore[attr-defined]
    except Exception as err:  # dbutils is optional; keep running without it
        print(f"connect_runner: dbutils unavailable ({err})", file=sys.stderr)


def main(argv: list[str] | None = None) -> None:
    options = parse_args(sys.argv[1:] if argv is None else argv)
    start = Path(options.file).resolve().parent if options.file else Path.cwd()
    compute = resolve(options, start, dict(os.environ))
    print(compute.describe(), file=sys.stderr)
    install_globals(create_session(compute), compute)

    if options.module:
        sys.argv = [options.module, *(options.args or [])]
        runpy.run_module(options.module, run_name="__main__", alter_sys=True)
    else:
        path = str(Path(options.file).resolve())
        sys.argv = [path, *(options.args or [])]
        sys.path.insert(0, str(Path(path).parent))
        runpy.run_path(path, run_name="__main__")


if __name__ == "__main__":
    main()
