"""Run (or debug) a local Python file against Databricks compute with Databricks Connect.

    python .zed/databricks/connect_runner.py FILE [ARGS...]
    python .zed/databricks/connect_runner.py -m MODULE [ARGS...]

Driver-side code runs locally, so debugpy breakpoints work as usual, while Spark work runs
remotely. Before running the file this creates the Databricks Connect session and provides
the Databricks runtime globals `spark`, `dbutils` and `display`, so notebook-style scripts
run unchanged.

Compute and profile come from Databricks Connect's own configuration: the environment
variables DATABRICKS_CONFIG_PROFILE, DATABRICKS_CLUSTER_ID and
DATABRICKS_SERVERLESS_COMPUTE_ID=auto, or `cluster_id` / `serverless_compute_id` in the
~/.databrickscfg profile. The runner only fills in what is not configured:
  - the profile and bundle target from the project's .zed/settings.json `terminal.env`, so
    debugging uses the same ones as Zed's tasks and diagnostics;
  - when no compute is configured, the bundle target's `cluster_id`, else serverless.

Needs `databricks-connect` in the Python environment running this script, in a version that
matches the compute; `databricks environments setup-local` (CLI v1.9.0+) sets that up.
Generated by zed-databricks; safe to edit.
"""

from __future__ import annotations

import builtins
import configparser
import json
import os
import runpy
import shutil
import subprocess
import sys
from collections.abc import MutableMapping
from dataclasses import dataclass, field
from pathlib import Path

PROFILE_ENV = "DATABRICKS_CONFIG_PROFILE"
TARGET_ENV = "DATABRICKS_BUNDLE_TARGET"
CLUSTER_ENV = "DATABRICKS_CLUSTER_ID"
SERVERLESS_ENV = "DATABRICKS_SERVERLESS_COMPUTE_ID"


@dataclass
class Invocation:
    file: str | None = None
    module: str | None = None
    args: list[str] = field(default_factory=list)


def parse_args(argv: list[str]) -> Invocation:
    if argv[:1] in (["-h"], ["--help"]):
        print(__doc__)
        raise SystemExit(0)
    if len(argv) >= 2 and argv[0] == "-m":
        return Invocation(module=argv[1], args=argv[2:])
    if argv and not argv[0].startswith("-"):
        return Invocation(file=argv[0], args=argv[1:])
    raise SystemExit("usage: connect_runner.py FILE [ARGS...] | -m MODULE [ARGS...]")


def strip_jsonc(text: str) -> str:
    """Remove comments and trailing commas: Zed settings are JSON with both."""
    return _scan(_scan(text, _skip_comment), _skip_trailing_comma)


def _skip_comment(text: str, i: int) -> int | None:
    """End index of a comment starting at `i`, or None if there is none."""
    if text.startswith("//", i):
        end = text.find("\n", i)
        return len(text) if end < 0 else end
    if text.startswith("/*", i):
        end = text.find("*/", i + 2)
        return len(text) if end < 0 else end + 2
    return None


def _skip_trailing_comma(text: str, i: int) -> int | None:
    if text[i] == "," and text[i + 1 :].lstrip()[:1] in ("}", "]"):
        return i + 1
    return None


def _scan(text: str, skip) -> str:
    """Copy `text`, dropping the spans `skip(text, i)` reports outside of string literals."""
    out, i, in_string = [], 0, False
    while i < len(text):
        c = text[i]
        if in_string:
            if c == "\\":
                out.append(text[i : i + 2])
                i += 2
                continue
            in_string = c != '"'
        elif c == '"':
            in_string = True
        elif (end := skip(text, i)) is not None:
            i = end
            continue
        out.append(c)
        i += 1
    return "".join(out)


def zed_terminal_env(start: Path) -> dict[str, str]:
    for directory in [start, *start.parents]:
        settings = directory / ".zed" / "settings.json"
        if settings.is_file():
            try:
                env = json.loads(strip_jsonc(settings.read_text())).get("terminal", {}).get("env", {})
            except (json.JSONDecodeError, AttributeError):
                return {}
            return {k: v for k, v in env.items() if isinstance(v, str)}
    return {}


def find_bundle_root(start: Path) -> Path | None:
    for directory in [start, *start.parents]:
        if (directory / "databricks.yml").is_file() or (directory / "databricks.yaml").is_file():
            return directory
    return None


def bundle_cluster_id(root: Path, target: str | None, profile: str | None) -> str | None:
    """`cluster_id` of the bundle target, from the CLI's resolved configuration."""
    cli = os.environ.get("DATABRICKS_CLI_PATH") or shutil.which("databricks")
    if not cli:
        return None
    command = [cli, "bundle", "validate", "--output", "json"]
    if target:
        command += ["--target", target]
    if profile:
        command += ["--profile", profile]
    try:
        # A failed validation still prints the resolved configuration, so the exit code is ignored.
        result = subprocess.run(command, cwd=root, capture_output=True, text=True, timeout=120, check=False)
        return (json.loads(result.stdout).get("bundle") or {}).get("cluster_id")
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        return None


def profile_sets_compute(profile: str | None, environ: MutableMapping[str, str]) -> bool:
    """Whether the ~/.databrickscfg profile already chooses a cluster or serverless."""
    # Databricks profiles don't inherit from DEFAULT, so don't let configparser do it.
    config = configparser.ConfigParser(default_section="\0", interpolation=None)
    config.read(environ.get("DATABRICKS_CONFIG_FILE") or Path.home() / ".databrickscfg")
    section = profile or "DEFAULT"
    if not config.has_section(section):
        return False
    return any(config[section].get(key) for key in ("cluster_id", "serverless_compute_id"))


def configure(start: Path, environ: MutableMapping[str, str]) -> str:
    """Fill in the Databricks Connect settings that aren't configured; describe the result."""
    terminal_env = zed_terminal_env(start)
    for name in (PROFILE_ENV, TARGET_ENV):
        if not environ.get(name) and terminal_env.get(name):
            environ[name] = terminal_env[name]
    profile = environ.get(PROFILE_ENV)
    using = f"profile {profile or 'DEFAULT'}"

    if environ.get(CLUSTER_ENV):
        return f"cluster {environ[CLUSTER_ENV]} ({CLUSTER_ENV}), {using}"
    if environ.get(SERVERLESS_ENV):
        return f"serverless ({SERVERLESS_ENV}), {using}"
    if profile_sets_compute(profile, environ):
        return f"compute from the {using}"
    target = environ.get(TARGET_ENV)
    if (root := find_bundle_root(start)) and (cluster := bundle_cluster_id(root, target, profile)):
        environ[CLUSTER_ENV] = cluster
        return f"cluster {cluster} (bundle target {target or '(default)'}), {using}"
    environ[SERVERLESS_ENV] = "auto"
    return f"serverless (default), {using}"


def install_globals(session, profile: str | None) -> None:
    """The names Databricks notebooks and jobs get for free."""
    builtins.spark = session  # type: ignore[attr-defined]

    def display(value: object = None, *args: object, **kwargs: object) -> None:
        show = getattr(value, "show", None)
        if callable(show) and hasattr(value, "schema"):  # a Spark DataFrame
            show(truncate=False)
        elif value is not None:
            print(value)

    builtins.display = display  # type: ignore[attr-defined]
    try:
        from databricks.sdk import WorkspaceClient

        builtins.dbutils = WorkspaceClient(profile=profile).dbutils  # type: ignore[attr-defined]
    except Exception as err:  # noqa: BLE001 - dbutils is optional; never let it stop the user's script
        print(f"connect_runner: dbutils unavailable ({err})", file=sys.stderr)


def missing_connect_message(python: str, start: Path) -> str:
    """Why `databricks.connect` can't be imported, and how to fix it."""
    lines = [f"connect_runner: databricks-connect is not installed for {python}."]
    root = find_bundle_root(start) or start
    venv_python = root / ".venv" / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    if venv_python.exists() and Path(python).resolve() != venv_python.resolve():
        lines.append(
            f"The project has {venv_python}, but a different Python ran this. In Zed, select it with"
            " `toolchain: select toolchain` (restart Zed if it isn't listed), then debug again."
        )
    else:
        lines.append(
            "Create the project's environment with the task `databricks: environments setup-local`"
            " (CLI v1.9.0+), then select `.venv` with `toolchain: select toolchain`."
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    invocation = parse_args(sys.argv[1:] if argv is None else argv)
    start = Path(invocation.file).resolve().parent if invocation.file else Path.cwd()
    print(f"Databricks Connect: {configure(start, os.environ)}", file=sys.stderr)

    try:
        from databricks.connect import DatabricksSession
    except ImportError:
        raise SystemExit(missing_connect_message(sys.executable, start)) from None

    install_globals(DatabricksSession.builder.getOrCreate(), os.environ.get(PROFILE_ENV))

    if invocation.module:
        sys.argv = [invocation.module, *invocation.args]
        runpy.run_module(invocation.module, run_name="__main__", alter_sys=True)
    else:
        path = str(Path(invocation.file or "").resolve())
        sys.argv = [path, *invocation.args]
        sys.path.insert(0, str(Path(path).parent))
        runpy.run_path(path, run_name="__main__")


if __name__ == "__main__":
    main()
