//! Zed extension for Databricks development.
//!
//! - Starts `databricks-bundle-ls`, which turns `databricks bundle validate` into diagnostics.
//! - Injects the bundle JSON schema, generated by the installed Databricks CLI, into Zed's
//!   `yaml-language-server`, so bundle files get completion, validation and hover docs. Only
//!   bundle files are mapped: other YAML in the worktree, and worktrees without a bundle, are
//!   left alone.

mod bundle_schema;

use std::fs;

use zed_extension_api::{self as zed, serde_json, settings::LspSettings, LanguageServerId, Result, Worktree};

const BUNDLE_LS: &str = "databricks-bundle-ls";
const YAML_LS: &str = "yaml-language-server";
const GITHUB_REPO: &str = "bartoszgajda55/zed-databricks";

#[derive(Default)]
struct DatabricksExtension {
    /// Path of a server binary this extension downloaded, reused for the rest of the session.
    downloaded_server: Option<String>,
    /// Absolute path of the generated schema, keyed by the CLI version that produced it.
    schema: Option<(String, String)>,
}

impl DatabricksExtension {
    fn server_binary(&mut self, id: &LanguageServerId, worktree: &Worktree) -> Result<String> {
        let settings = LspSettings::for_worktree(BUNDLE_LS, worktree).unwrap_or_default();
        if let Some(path) = settings.binary.and_then(|binary| binary.path) {
            return Ok(path);
        }
        if let Some(path) = worktree.which(BUNDLE_LS) {
            return Ok(path);
        }
        if let Some(path) = &self.downloaded_server {
            if fs::metadata(path).is_ok_and(|meta| meta.is_file()) {
                return Ok(path.clone());
            }
        }
        let path = self.download_server(id).map_err(|err| {
            format!(
                "{BUNDLE_LS} not found. Put it on PATH (`cargo install --path servers/{BUNDLE_LS}`), \
                 set lsp.{BUNDLE_LS}.binary.path, or publish a release. Download failed: {err}"
            )
        })?;
        self.downloaded_server = Some(path.clone());
        Ok(path)
    }

    fn download_server(&self, id: &LanguageServerId) -> Result<String> {
        zed::set_language_server_installation_status(id, &zed::LanguageServerInstallationStatus::CheckingForUpdate);
        let release = zed::latest_github_release(
            GITHUB_REPO,
            zed::GithubReleaseOptions {
                require_assets: true,
                pre_release: false,
            },
        )?;
        let (os, arch) = zed::current_platform();
        let target = bundle_schema::release_target(os, arch)?;
        let asset_name = format!("{BUNDLE_LS}-{target}.tar.gz");
        let asset = release
            .assets
            .iter()
            .find(|asset| asset.name == asset_name)
            .ok_or_else(|| format!("release {} has no asset {asset_name}", release.version))?;

        let version_dir = format!("{BUNDLE_LS}-{}", release.version);
        let binary = format!(
            "{version_dir}/{BUNDLE_LS}{}",
            if matches!(os, zed::Os::Windows) { ".exe" } else { "" }
        );
        if !fs::metadata(&binary).is_ok_and(|meta| meta.is_file()) {
            zed::set_language_server_installation_status(id, &zed::LanguageServerInstallationStatus::Downloading);
            zed::download_file(&asset.download_url, &version_dir, zed::DownloadedFileType::GzipTar)?;
            zed::make_file_executable(&binary)?;
            // Remove older downloads.
            for entry in fs::read_dir(".").map_err(|err| err.to_string())?.flatten() {
                let name = entry.file_name().to_string_lossy().into_owned();
                if name.starts_with(&format!("{BUNDLE_LS}-")) && name != version_dir {
                    fs::remove_dir_all(entry.path()).ok();
                }
            }
        }
        zed::set_language_server_installation_status(id, &zed::LanguageServerInstallationStatus::None);
        Ok(bundle_schema::absolute(&binary))
    }

    /// Generates `bundle-schema-<cli version>.json` in the extension's work directory, once per session
    /// (restart Zed after upgrading the CLI to pick up a new schema).
    fn ensure_schema(&mut self, worktree: &Worktree) -> Result<String> {
        if let Some((_, path)) = &self.schema {
            return Ok(path.clone());
        }
        let env = worktree.shell_env();
        let version_output = zed::process::Command::new("databricks")
            .arg("--version")
            .envs(env.clone())
            .output()?;
        let version = bundle_schema::parse_cli_version(&String::from_utf8_lossy(&version_output.stdout))
            .ok_or("could not determine the Databricks CLI version")?;

        let file = format!("bundle-schema-{version}.json");
        if !fs::metadata(&file).is_ok_and(|meta| meta.len() > 0) {
            let output = zed::process::Command::new("databricks")
                .args(["bundle", "schema"])
                .envs(env)
                .output()?;
            if output.status != Some(0) {
                return Err(format!(
                    "`databricks bundle schema` failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
            serde_json::from_slice::<serde_json::Value>(&output.stdout)
                .map_err(|err| format!("`databricks bundle schema` returned invalid JSON: {err}"))?;
            fs::write(&file, &output.stdout).map_err(|err| err.to_string())?;
        }
        let path = bundle_schema::absolute(&file);
        self.schema = Some((version, path.clone()));
        Ok(path)
    }
}

impl zed::Extension for DatabricksExtension {
    fn new() -> Self {
        Self::default()
    }

    fn language_server_command(&mut self, id: &LanguageServerId, worktree: &Worktree) -> Result<zed::Command> {
        if id.as_ref() != BUNDLE_LS {
            return Err(format!("unknown language server: {id}"));
        }
        let settings = LspSettings::for_worktree(BUNDLE_LS, worktree).unwrap_or_default();
        let (args, extra_env) = settings
            .binary
            .map(|binary| (binary.arguments.unwrap_or_default(), binary.env.unwrap_or_default()))
            .unwrap_or_default();
        let mut env = worktree.shell_env();
        env.extend(extra_env);
        Ok(zed::Command {
            command: self.server_binary(id, worktree)?,
            args,
            env,
        })
    }

    fn language_server_initialization_options(
        &mut self,
        _id: &LanguageServerId,
        worktree: &Worktree,
    ) -> Result<Option<serde_json::Value>> {
        let settings = LspSettings::for_worktree(BUNDLE_LS, worktree).unwrap_or_default();
        Ok(Some(bundle_schema::initialization_options(
            settings.initialization_options,
            worktree.which("databricks"),
        )))
    }

    fn language_server_workspace_configuration(
        &mut self,
        _id: &LanguageServerId,
        worktree: &Worktree,
    ) -> Result<Option<serde_json::Value>> {
        Ok(LspSettings::for_worktree(BUNDLE_LS, worktree)
            .ok()
            .and_then(|settings| settings.settings))
    }

    fn language_server_additional_workspace_configuration(
        &mut self,
        _id: &LanguageServerId,
        target_id: &LanguageServerId,
        worktree: &Worktree,
    ) -> Result<Option<serde_json::Value>> {
        if target_id.as_ref() != YAML_LS {
            return Ok(None);
        }
        let settings = LspSettings::for_worktree(BUNDLE_LS, worktree)
            .ok()
            .and_then(|s| s.settings);
        let root_is_bundle = ["databricks.yml", "databricks.yaml"]
            .iter()
            .any(|file| worktree.read_text_file(file).is_ok());
        let roots = bundle_schema::bundle_roots(settings.as_ref(), root_is_bundle);
        if roots.is_empty() {
            return Ok(None);
        }
        // Respect a mapping the user configured themselves (e.g. a pinned schema URL).
        let yaml_settings = LspSettings::for_worktree(YAML_LS, worktree)
            .ok()
            .and_then(|s| s.settings);
        if bundle_schema::user_maps_bundle_schema(yaml_settings.as_ref()) {
            return Ok(None);
        }
        let schema = match self.ensure_schema(worktree) {
            Ok(path) => path,
            // Without a local CLI, fall back to the schema of the latest CLI release.
            Err(_) => bundle_schema::LATEST_SCHEMA_URL.to_string(),
        };
        let globs = bundle_schema::bundle_file_globs(&worktree.root_path(), &roots);
        Ok(Some(bundle_schema::yaml_schema_configuration(&schema, &globs)))
    }
}

zed::register_extension!(DatabricksExtension);
